import React from "react"
import { DM_Sans, Roboto } from "next/font/google"
import Header from "@/components/Header"
import ReactQueryProvider from "@/providers/ReactQueryProvider"
import type { Metadata } from "next"
import "./globals.css"

const fontRoboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
})
const fontDMSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
})
export const metadata: Metadata = {
  title: "Halogenn",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${fontDMSans.variable} ${fontRoboto.variable} font-sans`}
      >
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
